version: "3.8"
services:
  app:
    restart: on-failure
    build:
      context: ./app
    expose:
      - "3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
